package entities;
// Generated Oct 20, 2016 10:21:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceId;
     private User user;
     private Date ngayMua;
     private Date ngayGiao;
     private String address;
     private Set invoiceDetails = new HashSet(0);

    public Invoice() {
    }

    public Invoice(User user, Date ngayMua, Date ngayGiao, String address, Set invoiceDetails) {
       this.user = user;
       this.ngayMua = ngayMua;
       this.ngayGiao = ngayGiao;
       this.address = address;
       this.invoiceDetails = invoiceDetails;
    }
   
    public Integer getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getNgayMua() {
        return this.ngayMua;
    }
    
    public void setNgayMua(Date ngayMua) {
        this.ngayMua = ngayMua;
    }
    public Date getNgayGiao() {
        return this.ngayGiao;
    }
    
    public void setNgayGiao(Date ngayGiao) {
        this.ngayGiao = ngayGiao;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getInvoiceDetails() {
        return this.invoiceDetails;
    }
    
    public void setInvoiceDetails(Set invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }




}


