package entities;
// Generated Oct 20, 2016 10:21:41 PM by Hibernate Tools 4.3.1



/**
 * InvoiceDetail generated by hbm2java
 */
public class InvoiceDetail  implements java.io.Serializable {


     private Integer invoiceDetailId;
     private Invoice invoice;
     private Watch watch;
     private Integer quantity;

    public InvoiceDetail() {
    }

	
    public InvoiceDetail(Invoice invoice, Watch watch) {
        this.invoice = invoice;
        this.watch = watch;
    }
    public InvoiceDetail(Invoice invoice, Watch watch, Integer quantity) {
       this.invoice = invoice;
       this.watch = watch;
       this.quantity = quantity;
    }
   
    public Integer getInvoiceDetailId() {
        return this.invoiceDetailId;
    }
    
    public void setInvoiceDetailId(Integer invoiceDetailId) {
        this.invoiceDetailId = invoiceDetailId;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Watch getWatch() {
        return this.watch;
    }
    
    public void setWatch(Watch watch) {
        this.watch = watch;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


