package entities;
// Generated Oct 20, 2016 10:21:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Watch generated by hbm2java
 */
public class Watch  implements java.io.Serializable {


     private Integer watchId;
     private Category category;
     private String name;
     private Integer quantity;
     private double price;
     private String image;
     private String description;
     private Set invoiceDetails = new HashSet(0);

    public Watch() {
    }

	
    public Watch(Category category, String name, double price) {
        this.category = category;
        this.name = name;
        this.price = price;
    }
    public Watch(Category category, String name, Integer quantity, double price, String image, String description, Set invoiceDetails) {
       this.category = category;
       this.name = name;
       this.quantity = quantity;
       this.price = price;
       this.image = image;
       this.description = description;
       this.invoiceDetails = invoiceDetails;
    }
   
    public Integer getWatchId() {
        return this.watchId;
    }
    
    public void setWatchId(Integer watchId) {
        this.watchId = watchId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getInvoiceDetails() {
        return this.invoiceDetails;
    }
    
    public void setInvoiceDetails(Set invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }




}


